FROM rust:1.49

RUN USER=root cargo new --bin blog
WORKDIR /blog

COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

RUN cargo build --release
RUN rm src/*.rs

COPY ./src ./src

RUN rm ./target/release/deps/blog*
RUN cargo install --path .

CMD ["blog"]